dist: bionic
language: java
addons:
  apt:
    packages:
      - ant
      - ant-optional
      - xvfb
matrix:
    include:
        - name: Build Load Master application
          jdk: openjdk12
          before_script:
            - cd Load\ Master/
          script: 
            - ant -Dnb.internal.action.name=build jar

        - name: Execute automated tests for basic functionality of Load Master
          jdk: openjdk12
          before_script:
            - cd Load\ Master/
          script: 
            - ant -Dnb.internal.action.name=test test
