dist: bionic
language: java
matrix:
    include:
        - name: Build Load Master application
          jdk: openjdk12
          before_script:
            - cd Load\ Master/
          script: 
            - ant $OPTS build

        - name: Execute automated tests for basic functionality of Load Master
          jdk: openjdk12
          env:
            - OPTS="-Djavac.compilerargs=-nowarn -Dbuild.compiler.deprecation=false"
          before_script:
            - cd Load\ Master/
          script: 
            - ant $OPTS test
