dist: bionic
language: java
matrix:
    include:
        - name: Build Load Master application
          jdk: openjdk12
          before_script:
            - cd Load\ Master/
          script: 
            - ant -Dnb.internal.action.name=build jar

        - name: Execute automated tests for basic functionality of Load Master
          jdk: openjdk12
          before_script:
            - cd Load\ Master/
            - mkdir /usr/share/
            - mkdir /usr/share/ant
            - mkdir /usr/share/ant/lib
            - cp lib/* /home/travis/.ant/lib
          script: 
            - ant -Dnb.internal.action.name=test test
