dist: bionic
language: java
addons:
  apt:
    packages:
      - ant
      - ant-optional
#      - xvfb
install:
  - export PATH="$PATH:$TRAVIS_BUILD_DIR/nbbuild/travis"
#  - export DISPLAY=:99.0
#  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sleep 3
matrix:
    include:
        - name: Build Load Master application
          jdk: openjdk12
          before_script:
            - cd Load\ Master/
          script: 
            - ant -Dnb.internal.action.name=build jar
#            - echo "==== 1/2 - Building application complete ===="

#        - name: Execute automated tests for basic functionality of Load Master
#          jdk: openjdk12
#          before_script:
#            - cd Load\ Master/
#          script: 
#            - ant -Dnb.internal.action.name=test test
#            - echo "==== 2/2 - Automated testing complete ===="
