/*
 * Copyright (C) 2020 PekinSOFT™ Systems
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * *****************************************************************************
 * 
 * Project :   Load Master™
 * Class   :   GeneralLedgerViewer
 * Author  :   Sean Carrick
 * Created :   Oct 22, 2020
 * Modified:   Oct 22, 2020
 * 
 * Purpose:
 *     [Provide a general purpose overview for this class]
 * 
 * WHEN          BY                  REASON
 * ------------  ------------------  -------------------------------------------
 * Oct 22, 2020  Sean Carrick        Initial creation.
 * 
 * *****************************************************************************
 */
package com.pekinsoft.loadmaster.view;

import com.pekinsoft.loadmaster.controller.ChartCtl;
import com.pekinsoft.loadmaster.controller.EntryCtl;
import com.pekinsoft.loadmaster.err.DataStoreException;
import com.pekinsoft.loadmaster.model.EntryModel;
import com.pekinsoft.loadmaster.utils.MessageBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sean Carrick &lt;sean at pekinsoft dot com&gt;
 */
public class GeneralLedgerViewer extends javax.swing.JInternalFrame {

    /**
     * Creates new form GeneralLedgerViewer
     */
    public GeneralLedgerViewer() {
        initComponents();
        
        // We are going to load the table right here in the constructor.
        DefaultTableModel model = (DefaultTableModel)glTable.getModel();
        
        try {
            EntryCtl ctl = new EntryCtl();
            
            for ( int x = 0; x < ctl.getRecordCount(); x++ ) {
                EntryModel data = ctl.get(x);
                
                ChartCtl coa = new ChartCtl();
                String fromAcct = "";
                String toAcct = "";
                
                // Get the name of the account for the from and the to accounts.
                for ( int y = 0; y < coa.getRecordCount(); y++ ) {
                    if ( coa.get(y).getNumber() == ctl.get(x).getFromAccount() )
                        fromAcct = coa.get(y).getName();
                    if ( coa.get(y).getNumber() == ctl.get(x).getToAccount() )
                        toAcct = coa.get(y).getName();
                }
                
                Object[] row = {data.getDateAsString(), // Tx date
                                data.getCode(),         // Tx code
                                data.getDescription(),  // Description of Tx
                                fromAcct,               // From account
                                toAcct,                 // To account
                                data.getAmount(),       // Tx amount
                                data.isDeductible(),    // Tax deductible
                                data.isBalanced()       // Balanced with bank.
                               };
                model.addRow(row);
            }
        } catch ( DataStoreException ex ) {
            MessageBox.showWarning("Something happened while reading in the General Ledger", "Error");
        }
        
        glTable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        glTable = new javax.swing.JTable();
        closeButton = new javax.swing.JButton();
        reverseButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("General Ledger");

        glTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tx Date", "Tx Code", "Description", "From Acct", "To Acct", "Amount", "Ded.", "Bal."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(glTable);
        if (glTable.getColumnModel().getColumnCount() > 0) {
            glTable.getColumnModel().getColumn(6).setResizable(false);
            glTable.getColumnModel().getColumn(7).setResizable(false);
        }

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pekinsoft/loadmaster/res/Cancel.png"))); // NOI18N
        closeButton.setMnemonic('C');
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        reverseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pekinsoft/loadmaster/res/Undo.png"))); // NOI18N
        reverseButton.setMnemonic('R');
        reverseButton.setText("Reverse Entry");
        reverseButton.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reverseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton)
                    .addComponent(reverseButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JTable glTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reverseButton;
    // End of variables declaration//GEN-END:variables
}
