/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pekinsoft.loadmaster.view;

import com.pekinsoft.loadmaster.Starter;
import com.pekinsoft.loadmaster.enums.SysExits;
import com.pekinsoft.loadmaster.utils.MessageBox;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JSeparator;

/**
 *
 * @author Sean Carrick
 */
public class LoadMaster extends javax.swing.JFrame {

    /**
     * Creates new form LoadMaster
     */
    public LoadMaster() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lrSplit = new javax.swing.JSplitPane();
        mainDesktop = new javax.swing.JDesktopPane();
        tbSplit = new javax.swing.JSplitPane();
        tasksContainer = new org.jdesktop.swingx.JXTaskPaneContainer();
        systemTasks = new org.jdesktop.swingx.JXTaskPane();
        loadTasks = new org.jdesktop.swingx.JXTaskPane();
        accountingTasks = new org.jdesktop.swingx.JXTaskPane();
        overviewPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        overView = new javax.swing.JTextArea();
        mainStatusBar = new org.jdesktop.swingx.JXStatusBar();
        tipsLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        loadProgressLabel = new javax.swing.JLabel();
        loadProgress = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Load Master");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lrSplit.setDividerLocation(250);
        lrSplit.setDividerSize(5);

        javax.swing.GroupLayout mainDesktopLayout = new javax.swing.GroupLayout(mainDesktop);
        mainDesktop.setLayout(mainDesktopLayout);
        mainDesktopLayout.setHorizontalGroup(
            mainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );
        mainDesktopLayout.setVerticalGroup(
            mainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );

        lrSplit.setRightComponent(mainDesktop);

        tbSplit.setDividerLocation(300);
        tbSplit.setDividerSize(5);
        tbSplit.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        systemTasks.setTitle("Load Master System");
        tasksContainer.add(systemTasks);

        loadTasks.setTitle("Loads");
        createLoadTasks();
        tasksContainer.add(loadTasks);

        accountingTasks.setTitle("Accounting");
        tasksContainer.add(accountingTasks);

        tbSplit.setTopComponent(tasksContainer);

        overView.setColumns(20);
        overView.setRows(5);
        jScrollPane1.setViewportView(overView);

        javax.swing.GroupLayout overviewPanelLayout = new javax.swing.GroupLayout(overviewPanel);
        overviewPanel.setLayout(overviewPanelLayout);
        overviewPanelLayout.setHorizontalGroup(
            overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
        );
        overviewPanelLayout.setVerticalGroup(
            overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        tbSplit.setRightComponent(overviewPanel);

        lrSplit.setLeftComponent(tbSplit);

        tipsLabel.setText("Watch here for helpful tips...");
        mainStatusBar.add(tipsLabel);
        mainStatusBar.add(jSeparator1);

        loadProgressLabel.setText("Load Progress:");
        mainStatusBar.add(loadProgressLabel);
        mainStatusBar.add(loadProgress);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lrSplit)
            .addComponent(mainStatusBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lrSplit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainStatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createLoadTasks() {
        loadTasks.add(new AbstractAction() {
        {
            putValue(Action.NAME, "Book New Load...");
            putValue(Action.SHORT_DESCRIPTION, "Displays the load booking dialog");
            putValue(Action.SMALL_ICON, new javax.swing.ImageIcon(getClass()
                    .getResource("/com/pekinsoft/loadmaster/res/add.png")));
        }

        public void actionPerformed(ActionEvent e) {
            doNewLoad();
        }
        });

        loadTasks.add(new JSeparator());

        loadTasks.add(new AbstractAction() {
        {
            putValue(Action.NAME, "Arrive at Stop...");
            putValue(Action.SHORT_DESCRIPTION, "Displays stop arrival dialog");
            putValue(Action.SMALL_ICON, new javax.swing.ImageIcon(getClass()
                    .getResource("/com/pekinsoft/loadmaster/res/Arrive.png")));
        }

        public void actionPerformed(ActionEvent e) {
            if ( getValue(Action.NAME).toString().equalsIgnoreCase("Arrive at Stop...") ) {
                putValue(Action.NAME, "Depart from Stop...");
                putValue(Action.SMALL_ICON, new javax.swing.ImageIcon(getClass()
                    .getResource("/com/pekinsoft/loadmaster/res/Depart.png")));
                doShowArrival();
            } else if ( getValue(Action.NAME).toString().equalsIgnoreCase("Depart from Stop...") ) {
                putValue(Action.NAME, "Arrive at Stop...");
                putValue(Action.SMALL_ICON, new javax.swing.ImageIcon(getClass()
                    .getResource("/com/pekinsoft/loadmaster/res/Arrive.png")));
                doShowDeparture();
            }
        }
        });

        loadTasks.add(new JSeparator());

        loadTasks.add(new AbstractAction() {
        {
            putValue(Action.NAME, "Take Cash Advance...");
            putValue(Action.SHORT_DESCRIPTION, "Displays cash advance dialog");
            putValue(Action.SMALL_ICON, new javax.swing.ImageIcon(getClass()
                    .getResource("/com/pekinsoft/loadmaster/res/money3D.png")));
        }

        public void actionPerformed(ActionEvent e) {
//            CashAdvanceDialog dlg = new CashAdvanceDialog(null, false);
//            dlg.pack();
//            dlg.setAlwaysOnTop(true);
//            dlg.setVisible(true);
        }
        });

        loadTasks.add(new JSeparator());

        loadTasks.add(new AbstractAction() {
        {
            putValue(Action.NAME, "View Loads Queue...");
            putValue(Action.SHORT_DESCRIPTION, "Displays Loads Queue dialog");
            putValue(Action.SMALL_ICON, new javax.swing.ImageIcon(getClass()
                    .getResource("/com/pekinsoft/loadmaster/res/freight.png")));
        }

        public void actionPerformed(ActionEvent e) {
            doShowLoadsQueue();
        }
        });
    }
    
    private void createSystemTasks() {
        
    }
    
    private void createAccountingTasks() {
        
    }
    
    private void doNewLoad() {
        Booker dlg = new Booker();
        
        dlg.pack();
        mainDesktop.add(dlg);
        dlg.setVisible(true);
    }
    
    private void doShowArrival() {
        
    }
    
    private void doShowDeparture() {
        
    }
    
    private void doShowLoadsQueue() {
        
    }
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Make sure that the user truly wants to exit the application.
        String msg = "Exit Load Master?";
        int response = MessageBox.askQuestion(msg, "Confirm Close", false);
        
        if ( response == MessageBox.YES_OPTION ) {
            Starter.exit(SysExits.EX_OK);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadMaster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXTaskPane accountingTasks;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JProgressBar loadProgress;
    private javax.swing.JLabel loadProgressLabel;
    private org.jdesktop.swingx.JXTaskPane loadTasks;
    private javax.swing.JSplitPane lrSplit;
    private javax.swing.JDesktopPane mainDesktop;
    private org.jdesktop.swingx.JXStatusBar mainStatusBar;
    private javax.swing.JTextArea overView;
    private javax.swing.JPanel overviewPanel;
    private org.jdesktop.swingx.JXTaskPane systemTasks;
    private org.jdesktop.swingx.JXTaskPaneContainer tasksContainer;
    private javax.swing.JSplitPane tbSplit;
    private javax.swing.JLabel tipsLabel;
    // End of variables declaration//GEN-END:variables
}
