/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pekinsoft.loadmaster.view;

import com.pekinsoft.loadmaster.Starter;
import com.pekinsoft.loadmaster.utils.ScreenUtils;
import java.awt.event.KeyEvent;

/**
 *
 * @author Sean Carrick
 */
public class SettingsDialog extends javax.swing.JDialog {

    /**
     * Creates new form SettingsDialog
     */
    public SettingsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setLocation(ScreenUtils.centerDialog(this));
        
        truckNumberField.setText(Starter.props.getProperty("truck.number", "[NOT SET]"));
        vinField.setText(Starter.props.getProperty("truck.vin", "[NOT SET]"));
        makeList.setSelectedItem(Starter.props.getProperty("truck.make", "Select Make..."));
        modelField.setText(Starter.props.getProperty("truck.model", "[NOT SET]"));
        odometerField.setText(Starter.props.getProperty("truck.start.odometer", "0"));
        trailerNumberField.setText(Starter.props.getProperty("trailer.number", "[NOT SET]"));
        trailerVINField.setText(Starter.props.getProperty("trailer.vin", "[NOT SET]"));
        trailerMakeField.setText(Starter.props.getProperty("trailer.make", "[NOT SET]"));
        trailerModelField.setText(Starter.props.getProperty("trailer.model", "[NOT SET]"));
        companyNameField.setText(Starter.props.getProperty("company.name", "[NOT SET]"));
        companyTypeList.setSelectedItem(Starter.props.getProperty("company.type", "Select Organization Type..."));
        chkAuthority.setSelected(Starter.props.getPropertyAsBoolean("authority", "false"));
    }

    private void doClose() {
        // Save the settings to the settings file.
        Starter.props.setProperty("truck.number", truckNumberField.getText());
        Starter.props.setProperty("truck.vin", vinField.getText());
        Starter.props.setProperty("truck.make", makeList.getSelectedItem().toString());
        Starter.props.setProperty("truck.model", modelField.getText());
        Starter.props.setProperty("truck.start.odometer", odometerField.getText());
        Starter.props.setProperty("trailer.number", trailerNumberField.getText());
        Starter.props.setProperty("trailer.vin", trailerVINField.getText());
        Starter.props.setProperty("trailer.make", trailerMakeField.getText());
        Starter.props.setProperty("trailer.model", trailerModelField.getText());
        Starter.props.setProperty("company.name", companyNameField.getText());
        Starter.props.setProperty("company.type", companyTypeList.getSelectedItem().toString());
        Starter.props.setPropertyAsBoolean("authority", chkAuthority.isSelected());
        
        Starter.props.flush();
        
        // Then, close the dialog.
        this.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingsTabbedPane = new javax.swing.JTabbedPane();
        generalTab = new javax.swing.JPanel();
        truckInfoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        truckNumberField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        makeList = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        modelField = new javax.swing.JTextField();
        vinField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        odometerField = new javax.swing.JFormattedTextField();
        tailerInfoPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        trailerNumberField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        trailerMakeField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        trailerModelField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        trailerVINField = new javax.swing.JTextField();
        companyInfoPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        companyNameField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        companyTypeList = new javax.swing.JComboBox<>();
        chkAuthority = new javax.swing.JCheckBox();
        commandPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        truckInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Truck Information"));

        jLabel1.setText("Truck #:");

        truckNumberField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                doSelection(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                doDeselection(evt);
            }
        });
        truckNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                checkEnterKey(evt);
            }
        });

        jLabel3.setText("Make:");

        makeList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Make...", "Freightliner", "Hino", "International", "Kenworth", "Peterbilt", "Sterling", "Scania", "Volvo", "Western Star" }));
        makeList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                checkEnterKey(evt);
            }
        });

        jLabel4.setText("Model:");

        modelField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                doSelection(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                doDeselection(evt);
            }
        });
        modelField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                checkEnterKey(evt);
            }
        });

        vinField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                doSelection(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                doDeselection(evt);
            }
        });
        vinField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                checkEnterKey(evt);
            }
        });

        jLabel5.setText("VIN:");

        jLabel6.setText("Starting Odometer:");

        odometerField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        odometerField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                doSelection(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                doDeselection(evt);
            }
        });
        odometerField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                checkEnterKey(evt);
            }
        });

        javax.swing.GroupLayout truckInfoPanelLayout = new javax.swing.GroupLayout(truckInfoPanel);
        truckInfoPanel.setLayout(truckInfoPanelLayout);
        truckInfoPanelLayout.setHorizontalGroup(
            truckInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(truckInfoPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(truckInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(truckInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(truckInfoPanelLayout.createSequentialGroup()
                        .addGroup(truckInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(truckNumberField)
                            .addComponent(makeList, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(truckInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(truckInfoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(odometerField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(truckInfoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modelField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(vinField))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        truckInfoPanelLayout.setVerticalGroup(
            truckInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(truckInfoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(truckInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(truckNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(truckInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(odometerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(truckInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(makeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(modelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(truckInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(vinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tailerInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Trailer Information"));

        jLabel2.setText("Trailer #:");

        trailerNumberField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                doSelection(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                doDeselection(evt);
            }
        });
        trailerNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                checkEnterKey(evt);
            }
        });

        jLabel7.setText("Make:");

        trailerMakeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                doSelection(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                doDeselection(evt);
            }
        });
        trailerMakeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                checkEnterKey(evt);
            }
        });

        jLabel8.setText("Model:");

        trailerModelField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                doSelection(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                doDeselection(evt);
            }
        });
        trailerModelField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                checkEnterKey(evt);
            }
        });

        jLabel9.setText("VIN:");

        trailerVINField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                doSelection(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                doDeselection(evt);
            }
        });
        trailerVINField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                checkEnterKey(evt);
            }
        });

        javax.swing.GroupLayout tailerInfoPanelLayout = new javax.swing.GroupLayout(tailerInfoPanel);
        tailerInfoPanel.setLayout(tailerInfoPanelLayout);
        tailerInfoPanelLayout.setHorizontalGroup(
            tailerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tailerInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tailerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tailerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tailerInfoPanelLayout.createSequentialGroup()
                        .addGroup(tailerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(trailerNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(trailerMakeField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trailerModelField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(trailerVINField))
                .addGap(39, 39, 39))
        );
        tailerInfoPanelLayout.setVerticalGroup(
            tailerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tailerInfoPanelLayout.createSequentialGroup()
                .addGroup(tailerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(trailerNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tailerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(trailerMakeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(trailerModelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tailerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(trailerVINField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        companyInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Company Information"));

        jLabel10.setText("Name:");

        companyNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                doSelection(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                doDeselection(evt);
            }
        });
        companyNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                checkEnterKey(evt);
            }
        });

        jLabel11.setText("Organization:");

        companyTypeList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Organization Type...", "Sole Proprietorship", "Limited Liability Company", "S-Corporation", "Corporation", "501(c)3 Corporation" }));
        companyTypeList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                checkEnterKey(evt);
            }
        });

        chkAuthority.setText("Have Own Authority");
        chkAuthority.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                checkEnterKey(evt);
            }
        });

        javax.swing.GroupLayout companyInfoPanelLayout = new javax.swing.GroupLayout(companyInfoPanel);
        companyInfoPanel.setLayout(companyInfoPanelLayout);
        companyInfoPanelLayout.setHorizontalGroup(
            companyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(companyInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(companyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(companyInfoPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(chkAuthority)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(companyInfoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(companyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(companyTypeList, 0, 1, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        companyInfoPanelLayout.setVerticalGroup(
            companyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(companyInfoPanelLayout.createSequentialGroup()
                .addGroup(companyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(companyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(companyTypeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkAuthority))
        );

        javax.swing.GroupLayout generalTabLayout = new javax.swing.GroupLayout(generalTab);
        generalTab.setLayout(generalTabLayout);
        generalTabLayout.setHorizontalGroup(
            generalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(truckInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tailerInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(companyInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        generalTabLayout.setVerticalGroup(
            generalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(truckInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tailerInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(companyInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        settingsTabbedPane.addTab("General", generalTab);

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pekinsoft/loadmaster/res/Cancel.png"))); // NOI18N
        closeButton.setMnemonic('C');
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout commandPanelLayout = new javax.swing.GroupLayout(commandPanel);
        commandPanel.setLayout(commandPanelLayout);
        commandPanelLayout.setHorizontalGroup(
            commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, commandPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
        );
        commandPanelLayout.setVerticalGroup(
            commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, commandPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(commandPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(settingsTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(settingsTabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(commandPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doSelection(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_doSelection
        if ( evt.getSource() instanceof javax.swing.JTextField )
            ((javax.swing.JTextField)evt.getSource()).selectAll();
    }//GEN-LAST:event_doSelection

    private void doDeselection(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_doDeselection
        if ( evt.getSource() instanceof javax.swing.JTextField )
            ((javax.swing.JTextField)evt.getSource()).select(0, 0);
    }//GEN-LAST:event_doDeselection

    private void checkEnterKey(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_checkEnterKey
        if ( evt.getKeyCode() == KeyEvent.VK_ENTER )
            doClose();
    }//GEN-LAST:event_checkEnterKey

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        doClose();
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SettingsDialog dialog = new SettingsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkAuthority;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel commandPanel;
    private javax.swing.JPanel companyInfoPanel;
    private javax.swing.JTextField companyNameField;
    private javax.swing.JComboBox<String> companyTypeList;
    private javax.swing.JPanel generalTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> makeList;
    private javax.swing.JTextField modelField;
    private javax.swing.JFormattedTextField odometerField;
    private javax.swing.JTabbedPane settingsTabbedPane;
    private javax.swing.JPanel tailerInfoPanel;
    private javax.swing.JTextField trailerMakeField;
    private javax.swing.JTextField trailerModelField;
    private javax.swing.JTextField trailerNumberField;
    private javax.swing.JTextField trailerVINField;
    private javax.swing.JPanel truckInfoPanel;
    private javax.swing.JTextField truckNumberField;
    private javax.swing.JTextField vinField;
    // End of variables declaration//GEN-END:variables
}
